### ISSUE TITLE
Install fails on node 10.14.2

### ISSUE THREAD

**Issue by stevage** [mapbox/node-mbtiles#87] opened 2018-12-18 21:44 UTC
```
$ n
node/10.14.2
Steves-MacBook-Pro-3 ~$ npm install @mapbox/mbtiles
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stevebennett/.npm/_logs/2018-12-18T21_40_16_075Z-debug.log
```

This is just a heads-up. Installing on node 10.0.0 worked.

More info:

```
2 info using npm@6.4.1
3 info using node@v10.14.2
4 verbose npm-session 0f98ffcb0835d2b9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose stack TypeError: asyncWrite is not a function
7 verbose stack     at onwrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:480:7)
7 verbose stack     at WritableState.onwrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:180:5)
7 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:154:13)
7 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
7 verbose stack     at WriteStream.Writable.write (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
7 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:171:25)
7 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
7 verbose stack     at WriteStream.Writable.write (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
7 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:182:19)
7 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
8 verbose cwd /Users/stevebennett/[...]
9 verbose Darwin 16.6.0
```

**Comment by sumarlidason** [comment] 2019-02-05 14:02
@stevage Did you get this sorted? I was unable to reproduce it today.

**Comment by stevage** [comment] 2019-02-06 11:34
Yep, still does the same. I have upgraded to Mojave since raising the issue. It installs fine with node 9.11.2 or 10.0.0.

Huh...but using `yarn` to install it on 10.14.2 did work. And then it runs fine too. So... not sure what to think. But that's really useful to know at least.

**Comment by jingsam** [comment] 2019-04-15 07:41
This problem is caused by switching different version of npm when using `n`. Close this  as it is not caused by node-mbtiles.

**Closed by jingsam** 2019-04-15 07:41 UTC
